name: alltheitems
main: com.daveestar.alltheitems.Main
version: 1.0.3
api-version: 26.2
authors: ["daveestar"]
commands:
  alltheitems:
    description: Opens the "All the Items" GUI.
    usage: /alltheitems
    aliases: [ati]
